[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.28"
optimizer = true
optimizer_runs = 1000000
via_ir = true
evm_version = "shanghai"

[rpc_endpoints]
# Avalanche Fuji Testnet
avalanche_fuji = "https://avalanche-fuji-c-chain-rpc.publicnode.com"

# Avalanche Mainnet (Multiple options)
avalanche_mainnet = "https://endpoints.omniatech.io/v1/avax/mainnet/public"
avalanche_mainnet_2 = "https://api.avax.network/ext/bc/C/rpc"

[etherscan]
avalanche_fuji = { key = "${ETHERSCAN_API_KEY}", url = "https://api-testnet.snowtrace.io/api" }
avalanche_mainnet = { key = "${ETHERSCAN_API_KEY}", url = "https://api.snowtrace.io/api" }