[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.28"
optimizer = true
optimizer_runs = 1000000
via_ir = true
evm_version = "shanghai"

[rpc_endpoints]
avalanche_fuji = "https://avalanche-fuji.drpc.org"
avalanche_mainnet = "https://avalanche.drpc.org"

[etherscan]
avalanche_fuji = { key = "${ETHERSCAN_API_KEY}", url = "https://api-testnet.snowtrace.io/api" }
avalanche_mainnet = { key = "${ETHERSCAN_API_KEY}", url = "https://api.snowtrace.io/api" }